-- Ideje za vodova srečanja
create table if not exists ideja (
  id bigint generated by default as identity primary key,
  vrsta text not null check (
    vrsta in ('Znanje', 'Zabavno', 'Ustvarjalno', 'Povezovalno')
  ),
  tema text not null,
  opis text not null,
  opombe text,
  created_at timestamptz not null default now()
);

-- Če je bila uporabljena prejšnja različica sheme, odstranimo povezavo na vodnika.
alter table ideja drop column if exists vodnik_id;

alter table ideja enable row level security;

drop policy if exists "public read ideja" on ideja;
create policy "public read ideja"
on ideja
for select
to anon
using (true);

revoke insert, update, delete on ideja from anon;
grant select on ideja to anon;
