-- Oglasna deska za medsebojno pomoč vodnikov
create table if not exists pomoc (
  id bigint generated by default as identity primary key,
  tip text not null check (
    tip in ('Iščem pomoč', 'Ponujam pomoč')
  ),
  vodnik_id bigint not null references vodnik(id),
  tema text not null,
  opis text not null,
  status text not null default 'Aktivno' check (
    status in ('Aktivno', 'Zaključeno')
  ),
  created_at timestamptz not null default now()
);

alter table pomoc enable row level security;

drop policy if exists "public read pomoc" on pomoc;
create policy "public read pomoc"
on pomoc
for select
to anon
using (true);

revoke insert, update, delete on pomoc from anon;
grant select on pomoc to anon;
